---
- name: installing utilities
  hosts: all 
  tasks:
    - name: install utilitiess
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ packages }}"  
    - name: debug variable
      ansible.builtin.debug:
        var: purpose  
    - name: inventory file name
      ansible.builtin.debug:
        var: inventory_file    