---
-name: installing utilities
 hosts: all 
 tasks:
   - name: install utilitiess
     ansible.builtin.package:
       name: "{{ item }}"
       state: present
     become: yes
     loop: "{{ packages }}"  