---
- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: creating tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: creating tomcat user     
      ansible.builtin.user:
        name: tomcat
        state: present 
        home: /opt/tomcat
        shell: /bin/false  
    - name: download tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
        dest: /tmp
    - name: extract tomcat
      ansible.builtin.unarchive:
        src: /tmp
        dest: /opt/tomcat
        remote_src: yes

            