---
- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: creating tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: creating tomcat user     
      ansible.builtin.user:
        name: tomcat
        create_home: true
        home: /opt/tomcat
        shell: /bin/false
        state: present   
    - name: download tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
        dest: /tmp/apache-tomcat-10.1.17
    - name: create opt/tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory    
    - name: extract tomcat tar file
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.1.17
        dest: /opt/tomcat/apache-tomcat-10.1.17
        remote_src: yes

            